### PR TITLE
Fix output format

### PR DESCRIPTION
**Pull request by ostcar**
The output format should be correct now.

@FinnStutzenstein could you check it? If you want, I can just merge it and you open an issue afterwards, if something does not work.

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
Hi,

I fixed two things, but I can't push into your fork. Plse see the last commit here: https://github.com/FinnStutzenstein/openslides3-autoupdate-service/tree/outputFormat

**Comment by ostcar** [comment]
I don't know way you can not push in my brach, but you can create a pull request to it. I did, merged your commit and added a small commit on top of it.

It should work now.

**Comment by FinnStutzenstein** [comment]
See https://github.com/ostcar/openslides3-autoupdate-service/pull/2

You can intive me into your repo, than I can push into it.

**Comment by ostcar** [comment]
> See [ostcar#2](https://github.com/ostcar/openslides3-autoupdate-service/pull/2)
> 
> You can intive me into your repo, than I can push into it.

done(?)

**Comment by FinnStutzenstein** [comment]
Why did you merge master into this branch before mergin it into master? It was rebased an had no conflicts

**Comment by ostcar** [comment]
There was a button on github that was called "update branch". I could not resist.

I thought, it would fast forward.

**Comment by FinnStutzenstein** [comment]
Hm, I guess we should stick to rebasing. Rebases and merges do not go well together :)

**Comment by ostcar** [comment]
Since I use "squash and merge" the commit history is clean.

**Comment by FinnStutzenstein** [comment]
In this case, yes :+1:

**Pull request merged**
