### PR TITLE
More health

### PR DESCRIPTION
**Pull request by ostcar**
@FinnStutzenstein Can you help me? This works when I build in in my repo.

But If I build this in the openslides-repo with build.sh I get an error, that there is no git-repository in the Dockerfile:

```
Step 10/21 : RUN go build -ldflags "-X main.commitHash=$(git rev-parse --short HEAD) -X main.commitDate=$(git log -1 --format=%ct)" ./cmd/autoupdate
 ---> Running in 8e7602c1540f
fatal: not a git repository: /root/../.git/modules/autoupdate
fatal: not a git repository: /root/../.git/modules/autoupdate
```

I added `ls -la` into the Dockerfile to see the content. There is an object called `.git` but it is not a directory:

```
Step 9/21 : RUN ls -la
 ---> Running in 62c05122299e
total 80
drwx------    1 root     root           182 Feb 27 00:23 .
drwxr-xr-x    1 root     root           138 Feb 27 00:23 ..
drwxr-xr-x    1 root     root            16 Feb 25 04:40 .cache
-rw-r--r--    1 root     root            35 Jan 28 19:39 .git
...
```
Do you understand why the content of the .git folder is copied in my repo but not, if it is build in the main repo? Is there some sort of dockerfile-ignore?

### CODE REVIEW

**Comment by ostcar** [comment]
@FinnStutzenstein I found the problem. In my repo, the .git/ folder is copies. But in the context of the submodule, the .git/ folder does not exist. There is only a file with the content `gitdir: ../.git/modules/autoupdate`.

Do you have an idea, how I could get the commit-id inside my dockerfile?

**Comment by ostcar** [comment]
@FinnStutzenstein I found a solution by creating the git-infos outside the dockerfile using a build.sh

I think, I have to use a specal --tag containing $img.

Could you have a look at it?

**Comment by FinnStutzenstein** [comment]
Have a look here: https://github.com/OpenSlides/OpenSlides/blob/master/server/build.sh

I would like to have a common format of this health/version status (also in hindsight of OS4). Maybe you can also include some more information, so the resulting json on /health looks like this:

```
{
  "healthy": true,
  "commit_hash": "...",
  "build_date": "...", <- Simpel output of date in the build.sh
  "info": "..." <- Here, you can put extra non standard info. E.g. your current version string.
}
```

I would like to do this also for the client and server, so each service has a /health with these information. Unification would help for the server tools I guess.

**Comment by ostcar** [comment]
I close this for os3. Maybe we can talk about this for os4 at another place.

**Pull request closed without merging**
